materia:
    path:     /
    defaults: { _controller: "AVBundle:Materia:index" }

materia_show:
    path:     /{id}/show
    defaults: { _controller: "AVBundle:Materia:show" }

materia_new:
    path:     /new
    defaults: { _controller: "AVBundle:Materia:new" }

materia_create:
    path:     /create
    defaults: { _controller: "AVBundle:Materia:create" }
    methods:  POST

materia_edit:
    path:     /{id}/edit
    defaults: { _controller: "AVBundle:Materia:edit" }

materia_update:
    path:     /{id}/update
    defaults: { _controller: "AVBundle:Materia:update" }
    methods:  [POST, PUT]

materia_delete:
    path:     /{id}/delete
    defaults: { _controller: "AVBundle:Materia:delete" }
    methods:  [POST, DELETE]
