reto:
    path:     /
    defaults: { _controller: "AVBundle:Reto:index" }

reto_show:
    path:     /{id}/show
    defaults: { _controller: "AVBundle:Reto:show" }

reto_new:
    path:     /new
    defaults: { _controller: "AVBundle:Reto:new" }

reto_create:
    path:     /create
    defaults: { _controller: "AVBundle:Reto:create" }
    methods:  POST

reto_edit:
    path:     /{id}/edit
    defaults: { _controller: "AVBundle:Reto:edit" }

reto_update:
    path:     /{id}/update
    defaults: { _controller: "AVBundle:Reto:update" }
    methods:  [POST, PUT]

reto_delete:
    path:     /{id}/delete
    defaults: { _controller: "AVBundle:Reto:delete" }
    methods:  [POST, DELETE]
misretos:
    path:     /{idg}/misRetos
    defaults: { _controller: "AVBundle:Reto:MisRetos" }