login_route:
    path:     /login
    defaults: { _controller: AVBundle:Seguridad:login }
validar_login:
    path: /validar_login
logout:
    path: /logout
av:
    resource: "@AVBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
app_olvidoClave:
    path:     /olvideClave
    defaults: { _controller: "AVBundle:Seguridad:olvideClave" }
    methods:  POST 